openapi: 3.0.1
info:
  title: Simple Social Media Application API
  version: 1.0.0
  description: API for a basic social networking service with posts, comments, and likes.
servers:
  - url: /api
paths:
  /posts:
    get:
      summary: List all posts
      responses:
        '200':
          description: A list of posts
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Post created
  /posts/{postId}:
    get:
      summary: Get a single post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Post details
    patch:
      summary: Update a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Post updated
    delete:
      summary: Delete a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Post deleted
  /posts/{postId}/comments:
    get:
      summary: List comments for a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of comments
    post:
      summary: Create a comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Comment created
  /posts/{postId}/comments/{commentId}:
    get:
      summary: Get a specific comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Comment details
    patch:
      summary: Update a comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Comment updated
    delete:
      summary: Delete a comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Comment deleted
  /posts/{postId}/likes:
    post:
      summary: Like a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '201':
          description: Like added
    delete:
      summary: Unlike a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Like removed
